whisper:
  inference:
    ros__parameters:
      # whisper
      model_name: "base.en" # other models https://huggingface.co/ggerganov/whisper.cpp
      wparams:
        language: "en"
        print_progress: false
        n_threads: 8
      cparams:
        flash_attn: true
        gpu_device: 0
        use_gpu: true

      # buffer
      buffer_capacity: 3 # seconds
      callback_ms: 1000 # milliseconds
